name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
        architecture: x64
    - run: pip install nox==2024.4.15
    - run: pip install poetry==1.8.2
    - run: pip install nox_poetry==1.0.3
    - run: nox --sessions tests-3.9 coverage
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
